apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    tier: mysql
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: deploy-mysql
spec:
  template:
    metadata:
      name: mysql
      labels:
        tier: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:5.7
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          value: test
        - name: MYSQL_USER
          value: test
        - name: MYSQL_PASSWORD
          value: test
        - name: MYSQL_DATABASE
          value: todolist
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory